### PR TITLE
bumping dependency and adding exclusions to remove warnings

### PR DESCRIPTION
**Pull request by tgalery**
Like the tin says. I was getting annoyed with some warning the dependency was throwing, so this is a version bump plus some exclusions. Tests were failing before the version bump so it doesn't like it's causing a build fail. Still not completely sure if stuff got broken. Thoughts would be appreciated.

### CODE REVIEW

**Comment by alxlit** [comment]
Thanks! Didn't mean to sit on this. Will put together a release after sorting out #10 sometime soon (hopefully).

**Comment by tgalery** [comment]
No worries, thank you!

**Comment by tokenshift** [comment]
@alxlit any chance of a new release with this merge? I'm running into the same dependency warnings.

**Comment by alxlit** [comment]
I think at this point I should just do a 0.2.0 release. I will bump the version numbers, update tests, and add exclusions to make the version range warning go away. Does that sound okay?

**Comment by tokenshift** [comment]
Sounds great. Thanks!

**Pull request merged**
